/**
 * Regenerates `public/sitemap.xml` from the same on-disk archive `getPrerenderParams` reads
 * (`src/app/app.routes.server.ts`), so the sitemap and the set of files the build actually emits
 * can never drift apart.
 *
 * Only prerendered public routes are listed. A sitemap that advertises an address Pages answers
 * 404 for is a crawl-quality signal against the whole site, which is exactly what the hand-written
 * predecessor did with `/athletes` (a client-side `redirectTo` with no server route). `/timer` and
 * `/admin` are prerendered too but deliberately left out: the stopwatch is a tool for the organiser,
 * not a landing page, and neither has anything to rank for. `/athletes/:key` and `/vs/:left/:right`
 * stay out until they are prerendered (docs/AUDIT.md § 46).
 *
 * Usage: bun scripts/build-sitemap.ts (runs before `bun run build` / `bun run start`).
 * Idempotent: the emitted file is committed, so a fresh checkout already carries a valid sitemap
 * even before the first build.
 */
import { Database } from 'bun:sqlite';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

import { CANONICAL_SITE_BASE_URL } from '../src/app/shared/seo/canonical-link.constant';

const DB_PATH = 'data/sundayrun.db';
const TARGET = 'public/sitemap.xml';
/** 'YYYY' of an ISO date — the slug doubles as the event date, so it also names the year review. */
const ISO_YEAR_LENGTH = 4;

interface SitemapEntry {
  changefreq: string;
  /** Absent for pages whose content follows the code rather than the archive. */
  lastmod?: string;
  /** Route path without the leading slash; '' is the home page. */
  path: string;
  priority: string;
}

/**
 * The archive is republished every Sunday, so every hub page changes with it; `/guide` describes
 * features and moves with releases instead, and gets no `lastmod` rather than a fabricated one.
 */
const staticEntries = (newestEventDate: string | undefined): SitemapEntry[] => [
  { changefreq: 'weekly', lastmod: newestEventDate, path: '', priority: '1.0' },
  { changefreq: 'weekly', lastmod: newestEventDate, path: 'races', priority: '0.9' },
  { changefreq: 'weekly', lastmod: newestEventDate, path: 'records', priority: '0.7' },
  { changefreq: 'weekly', lastmod: newestEventDate, path: 'year', priority: '0.7' },
  { changefreq: 'monthly', lastmod: newestEventDate, path: 'vs', priority: '0.5' },
  { changefreq: 'monthly', path: 'guide', priority: '0.5' },
];

/**
 * The deploy lives under the `/sundayrun/` base href, and sitemap `<loc>` must be absolute, so the
 * canonical base is reused verbatim — the same string `CanonicalLinkService` writes into `<head>`.
 * The home page keeps its trailing slash; every other path is appended without one, matching the
 * urls Pages serves and the canonical links the pages themselves declare.
 */
const toXmlUrl = ({ changefreq, lastmod, path, priority }: SitemapEntry): string => {
  const lines = [
    `    <loc>${CANONICAL_SITE_BASE_URL}/${path}</loc>`,
    ...(lastmod === undefined ? [] : [`    <lastmod>${lastmod}</lastmod>`]),
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
  ];

  return `  <url>\n${lines.join('\n')}\n  </url>`;
};

const db = new Database(DB_PATH);
// Newest first: slugs and years are ISO dates, so a date sort is also the site's own ordering.
const events = db.query<{ date_iso: string; slug: string }, []>('SELECT slug, date_iso FROM events ORDER BY date_iso DESC').all();

db.close();

// The first row of a year is its newest event, which is when that year's review last changed.
const lastmodByYear = new Map<string, string>();

for (const { date_iso: dateIso, slug } of events) {
  const year = slug.slice(0, ISO_YEAR_LENGTH);

  if (!lastmodByYear.has(year)) {
    lastmodByYear.set(year, dateIso);
  }
}

const eventEntries: SitemapEntry[] = events.map(({ date_iso: dateIso, slug }) => ({
  changefreq: 'yearly',
  lastmod: dateIso,
  path: `races/${slug}`,
  priority: '0.6',
}));

const yearEntries: SitemapEntry[] = [...lastmodByYear.entries()].map(([year, lastmod]) => ({
  changefreq: 'monthly',
  lastmod,
  path: `year/${year}`,
  priority: '0.6',
}));

const entries = [...staticEntries(events.at(0)?.date_iso), ...eventEntries, ...yearEntries];
const content = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.ts from data/sundayrun.db — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map(toXmlUrl).join('\n')}
</urlset>
`;

const summary = `${entries.length} urls: ${eventEntries.length} protocols, ${yearEntries.length} year reviews`;

// Written only when the bytes actually change. A code push leaves the archive untouched, so the
// build must not dirty the working tree: CI commits the version bump before building and falls back
// to `git rebase` when the push races, and a rebase refuses to run over unstaged changes.
if (existsSync(TARGET) && readFileSync(TARGET, 'utf8') === content) {
  console.log(`${TARGET} is up to date (${summary})`);
} else {
  writeFileSync(TARGET, content);
  console.log(`Wrote ${TARGET} (${summary})`);
}
