import { writeFileSync } from 'node:fs';

/**
 * Bakes the package.json version into `src/app/core/app-version.constant.ts`, so the header badge
 * always shows the built version. Runs before every `build`/`start`; CI bumps package.json on a
 * code push (never a data-only publication), and this writes that number into the bundle.
 */
const { version } = (await Bun.file('package.json').json()) as { version: string };

const target = 'src/app/core/app-version.constant.ts';
const content = `// Generated by scripts/write-version.ts from package.json — do not edit by hand.
export const APP_VERSION = '${version}';
`;

writeFileSync(target, content);
console.log(`Wrote ${target} (APP_VERSION = ${version})`);
